### PR TITLE
add support for TickSize

### PR DESCRIPTION
**Pull request by shekenahglory**

### CODE REVIEW

**Comment by wilsonianb** [comment]
Can you add the following here:
https://github.com/ripple/ripple-binary-codec/blob/de0f68a1b9b94db1938b26f11ae39be3aa4a16b0/test/fixtures/data-driven-tests.json#L877
```
        {
            "type_name": "UInt8",
            "name": "TickSize",
            "nth_of_type": 16,
            "type": 16,
            "expected_hex": "01010"
        },
```

**Comment by wilsonianb** [comment]
Either update the version number in the commit message or separate the version bump in its own commit.

**Comment by shekenahglory** [comment]
updated - I removed the version bump, maybe it should happen after both PR's are merged

**Comment by wilsonianb** [comment]
It looks like we also need `temBAD_TICK_SIZE`
https://github.com/ripple/rippled/pull/1922/files#diff-7d3e571ee9542d0c0286414d7d9d29aaR88

**Comment by shekenahglory** [comment]
added `temBAD_TICK_SIZE`

**Comment by wilsonianb** [comment]
LGTM :+1:

**Pull request merged**
