### PR TITLE
Remove unused 'signing' code

### PR DESCRIPTION
**Pull request by intelliot**
Someone correct me if I'm wrong, but it doesn't look like this code is used. ripple-lib and/or ripple-keypairs should be used for signing.

### CODE REVIEW

**Comment by sublimator** [comment]
@intelliot 

image

There's a bunch unused. This was written for internal use only for a rippled test suite I had started to work on.  e.g. https://github.com/ripple/ripple-binary-codec/blob/master/src/shamap.js

The reason so, is that this was originally "ripple-core" but Clark copy/pasted/borrowed the code for the new RippleAPI library. I think he intended to make it all modular, with this exporting a very minimal api:
https://github.com/ripple/ripple-binary-codec/blob/8b6717b964d90e6df03fd3b708650f11267256ff/src/index.js#L64-L72

But it ended up that ripple-hashes implemented ShaMap [as well](https://github.com/ripple/ripple-hashes/blob/master/src/shamap.js), and then depended upon this lib for encoding the leaves :) Kind of defeated the purpose. 

iirc, this impl of ShaMap was considerably faster (doubly so iirc) than the ripple-hashes one, taken from the original ripple-lib. 

Have you considered creating a lerna/yarn workspaces monorepo for all these libraries ?

**Comment by intelliot** [comment]
I would be fine with that, though I think there is a little bit of a learning curve. There's some value in the simplicity of separate repos (as long as the number of libraries is relatively small). Dependencies are easier to handle and maintain when there are just 2-3 as opposed to 20-30. I'd prefer to reduce dependencies unless it _really_ makes sense to have separate libraries.

**Comment by keefertaylor** [comment]
> Have you considered creating a lerna/yarn workspaces monorepo for all these libraries ?
Agree with Elliot that for separate, mostly unrelated packages, a mono repo doesn't buy us much in terms of packaging and costs a lot in developer ramp up time and requires another tool. Unless there's a real overriding desire, I don't see the point in moving to a mono repo. 

> There's a bunch unused.
IMO we should be aggressive about cleaning up dead code. We have version history in git we can always use to get it back if we need it, and it simplifies lives for both developers and clients.

**Comment by sublimator** [comment]
> Unless there's a real overriding desire, I don't see the point in moving
to a mono repo.

It’s easier to get a known working set and easier to develop them all in
tandem without having to manually link them.

You can actually set up a root tsconfig for the IDE to look at the set of
sources as a whole so all the TypeScript nav/refactoring works across the
whole monorepo. Project references etc. Easier to maintain consistency with
shared lint/typescript config.

I guess now that the libs are largely in maintenance/bugfix mode, it’s not
that big a win.

ripple-address-codec
ripple-keypairs
ripple-binary-codec
ripple-lib-transactionparser
ripple-hashes
ripple-lib
ripple-lib-orderbook
ripple-lib-value
ripple-lib-messagesigner

Seems more than two or three :)
Any others?

Message signer not really used? A monorepo would convey that.

Yeahp, like other tools, there’s a learning curve. And what makes sense for
some isn’t always apparent to others as can be missing some perspective.

You can go the monolithic package (a legitimate choice, but unfortunately
that ship has sailed) route or separate packages. If you choose the latter
there are good tools for managing them in one repo.

Your mileage may vary.

**Pull request merged**
