### PR TITLE
Fix: Signature is a non-signing field

### PR DESCRIPTION
**Pull request by sharafian**
This was causing errors when signing PaymentChannelClaim transactions in ripple lib

### CODE REVIEW

**Comment by vinniefalco** [comment]
If I'm reading this right, you're saying that the signature field should not be included in the fields used to calculate the digest of the transaction. If so, then that is correct.

**Comment by sharafian** [comment]
@vinniefalco yeah, that's right

**Comment by sublimator** [comment]
Oops: https://github.com/ripple/rippled/pull/1972

**Comment by sublimator** [comment]
https://github.com/ripple/rippled/blob/develop/bin/update_binformat.js

**Comment by wilsonianb** [comment]
Consider adding a `TxnSignature` and/or `Signature` field here to test
https://github.com/ripple/ripple-binary-codec/blob/master/test/signing-data-encoding-test.js#L15

**Comment by sharafian** [comment]
Added those fields to the tests

**Pull request merged**
