### PR TITLE
fix(tickets): Field codes for TicketCount and TicketSequence

### PR DESCRIPTION
**Pull request by elmurci**
BeginLedgerSeq was taking the place of `TicketCount` (40) in definitions.
From [rippled's code](https://github.com/ripple/rippled/blob/a8d481c2a54267d80bd539003f56481424b9ae63/src/ripple/protocol/impl/SField.cpp#L120-121
) `TicketCount` should be **40** and `TicketSequence` **41**.
Also, `BeginLedgerSeq` doesn't seem to be used, so removing it.

### CODE REVIEW

**Comment by natenichols** [comment]
Would you resolve the merge conflict?

**Review by natenichols — APPROVED** [review]
LGTM 👍 
Once the conflict is resolved I'll spin this into another beta.

**Comment by natenichols** [comment]
To fix the CI/CD change the `ticket-create-binary.json` to `12000A240000000E2028000000016840000000000027108114D5024F157225CA9F8F4C73094D61A8FDD746E0DB`

**Comment by intelliot** [comment]
What is `BeginLedgerSeq` and where did it come from? @natenichols it looks like you added it here: https://github.com/ripple/ripple-binary-codec/commit/2ffb464dc0ac9cd9896f677a4acd2b9b86c0426e

**Comment by natenichols** [comment]
This one is totally my bad. 
While this PR was being reviewed there were some changes made to the PR for negative UNL SFields.cpp

IIRC those changes made `UNLModify` txs  use `LedgerSequence` instead of `BeginLedgerSequence`. Looks like it slipped through on the PR. 

It is no longer in the [rippled code]( https://github.com/ripple/rippled/blob/a8d481c2a54267d80bd539003f56481424b9ae63/src/ripple/protocol/impl/SField.cpp#L120-L121) as mentioned above

**Pull request merged**
