### PR TITLE
dont validate amounts coming from binary parser

### PR DESCRIPTION
**Pull request by shekenahglory**

### CODE REVIEW

**Comment by intelliot** [comment]
What’s the motivation for this change?

**Comment by shekenahglory** [comment]
the data API uses this but throws an error parsing a handful of older transactions that somehow had what are now considered invalid amounts.  I’m wondering if it would be problematic to simply skip the validation check when an Amount object is being created from serialized data?

**Comment by sublimator** [comment]
You use the Amount object directly?

**Comment by sublimator** [comment]
I actually wrote this libray for a test suite I was writing for rippled.
That version exported all the types.

Another ripple dev inlined it to this repo, exporting only a simple
interface as RippleAPI would need. Subsequently, a separate ripple-hashes
library was created. Amusingly, this library implements a shamap tree.
Amusing because while the hashes library does also, it ended up importing
this lib for encoding json leaf nodes to binary ... so much for modular
little libs.

Anyway, interesting to me in that context that you might be using the
Amount class directly.

The objects were supposed to be immutable in practice (no setters) if not
policy, and if you had an instance of a given object, it should be valid
due to to constructor time validation. That was the target anyway.

From doing a heap early ledger processing I noticed there’s really only one
amount in old ledgers that’s a problem. It was an XRP amount, which was
TakerPays in some old offer. It serializes just fine as it’s not so big it
overflows, but it was larger than the total XRP in existence.

You can just special case it and in practice it works out fine as rippled
no longer allows new dodgy amounts into the ledger. It feels gross though.
But yeah ...

Potentially more annoying for history processing is the repurposing of
field codes for new fields ...

**Pull request merged**
